version: '3' # specify docker-compose version

services:
  client:
    build: ../client
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - "./config.js:/usr/src/app/config.js"
    restart: always
    depends_on:
      - "server"
    command: ./wait-for-it.sh -t 0 server:4000 -- npm start

  server:
    build: ../server
    container_name: server
    ports:
      - "4000:4000"
    volumes:
      - "./files:/usr/src/app/files"
      - "./images:/usr/src/app/images"
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - "mysql"
    links:
      - "mysql"
    command: ./wait-for-it.sh -t 0 mysql:3306 -- npm start

  mysql:
    image: mysql:5.6
    container_name: mysql
    volumes:
      - "./sql_init:/docker-entrypoint-initdb.d"
      - "./mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'wbat_alwaysdata'
    restart: always